 use('Colecciones');

 db.Artistas.find();
 db.Artistas.find({ nombre: {$gt:"Pablo Picasso" }});
 db.Artistas.find({ obra: {$gt:"Guernica" }});
 db.Artistas.find({ nombre: {$gt:"Frida Kahlo" }});
 db.Artistas.find({ obra: {$gt:"La columna rota" }});
 db.Artistas.find({ nombre: {$gt:"Vincent van Gogh" }});
 db.Artistas.find({ obra: {$gt:"La noche estrellada" }});
 db.Artistas.find({ nombre: {$gt:"Salvador Dalí" }});
 db.Artistas.find({ obra: {$gt:"La persistencia de la memoria" }});
 db.Artistas.find({ nombre: {$gt:"Claude Monet" }});
 db.Artistas.find({ obra: {$gt:"Impresión, sol naciente" }});
 db.Artistas.find({ nombre: {$gt:"Andy Warhol" }});
 db.Artistas.find({ obra: {$gt:"Campbell's Soup Cans" }});
 db.Artistas.find({ nombre: {$gt:"Leonardo Da Vinci" }});
 db.Artistas.find({ obra: {$gt:"La Mona Lisa" }});
 db.Artistas.find({ nombre: {$gt:"Michelangelo Buonarroti" }});
 db.Artistas.find({ obra: {$gt:"La creación de Adán" }});
 db.Artistas.find({ nombre: {$gt:"Henri Matisse" }});
 db.Artistas.find({ obra: {$gt:"La danza" }});
 db.Artistas.find({ nombre: {$gt:"Georgia O'Keeffe" }});
 db.Artistas.find({ obra: {$gt:"Flores rojas" }});

 db.Cantantes.find();

 db.Cantantes.find({ nombre: {$gt:"Diego" }});
 db.Cantantes.find({ edad: { $gt: 17 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Jota" }}); 
 db.Cantantes.find({ edad: { $gt: 22 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Dann" }}); 
 db.Cantantes.find({ edad: { $gt: 21 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Smoke" }}); 
 db.Cantantes.find({ edad: { $gt: 22 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Jorge" }}); 
 db.Cantantes.find({ edad: { $gt: 19 }});
 db.Cantantes.find({ grupo: "Solista" });
 db.Cantantes.find({ nombre: { $gt: "German" }}); 
 db.Cantantes.find({ edad: { $gt: 22 }});
 db.Cantantes.find({ grupo: "DAAZ" });
 db.Cantantes.find({ nombre: { $gt: "Harry" }}); 
 db.Cantantes.find({ edad: { $gt: 31 }});
 db.Cantantes.find({ grupo: "One Direction" });
 db.Cantantes.find({ nombre: { $gt: "Liam" }}); 
 db.Cantantes.find({ edad: { $gt: 32 }});
 db.Cantantes.find({ grupo: "One Direction" });
 db.Cantantes.find({ nombre: { $gt: "Jungkook" }}); 
 db.Cantantes.find({ edad: { $gt: 28 }});
 db.Cantantes.find({ grupo: "BTS" });
 db.Cantantes.find({ nombre: { $gt: "Jimin" }}); 
 db.Cantantes.find({ edad: { $gt: 30 }});
 db.Cantantes.find({ grupo: "BTS" });