 use('Colecciones');

 db.Artistas.find();
 db.Artistas.find({ nombre: {$gt:"Pablo Picasso" }});
 db.Artistas.find({ obra: {$gt:"Guernica" }});
 db.Artistas.find({ nombre: {$gt:"Frida Kahlo" }});
 db.Artistas.find({ obra: {$gt:"La columna rota" }});
 db.Artistas.find({ nombre: {$gt:"Vincent van Gogh" }});
 db.Artistas.find({ obra: {$gt:"La noche estrellada" }});
 db.Artistas.find({ nombre: {$gt:"Salvador Dalí" }});
 db.Artistas.find({ obra: {$gt:"La persistencia de la memoria" }});
 db.Artistas.find({ nombre: {$gt:"Claude Monet" }});
 db.Artistas.find({ obra: {$gt:"Impresión, sol naciente" }});
 db.Artistas.find({ nombre: {$gt:"Andy Warhol" }});
 db.Artistas.find({ obra: {$gt:"Campbell's Soup Cans" }});
 db.Artistas.find({ nombre: {$gt:"Leonardo Da Vinci" }});
 db.Artistas.find({ obra: {$gt:"La Mona Lisa" }});
 db.Artistas.find({ nombre: {$gt:"Michelangelo Buonarroti" }});
 db.Artistas.find({ obra: {$gt:"La creación de Adán" }});
 db.Artistas.find({ nombre: {$gt:"Henri Matisse" }});
 db.Artistas.find({ obra: {$gt:"La danza" }});
 db.Artistas.find({ nombre: {$gt:"Georgia O'Keeffe" }});
 db.Artistas.find({ obra: {$gt:"Flores rojas" }});

 db.Cantantes.find();
 db.Cantantes.find({ nombre: {$gt:"Diego" }});
 db.Cantantes.find({ edad: { $gt: 17 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Jota" }}); 
 db.Cantantes.find({ edad: { $gt: 22 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Dann" }}); 
 db.Cantantes.find({ edad: { $gt: 21 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Smoke" }}); 
 db.Cantantes.find({ edad: { $gt: 22 }});
 db.Cantantes.find({ grupo: "Wiplash" });
 db.Cantantes.find({ nombre: { $gt: "Jorge" }}); 
 db.Cantantes.find({ edad: { $gt: 19 }});
 db.Cantantes.find({ grupo: "Solista" });
 db.Cantantes.find({ nombre: { $gt: "German" }}); 
 db.Cantantes.find({ edad: { $gt: 22 }});
 db.Cantantes.find({ grupo: "DAAZ" });
 db.Cantantes.find({ nombre: { $gt: "Harry" }}); 
 db.Cantantes.find({ edad: { $gt: 31 }});
 db.Cantantes.find({ grupo: "One Direction" });
 db.Cantantes.find({ nombre: { $gt: "Liam" }}); 
 db.Cantantes.find({ edad: { $gt: 32 }});
 db.Cantantes.find({ grupo: "One Direction" });
 db.Cantantes.find({ nombre: { $gt: "Jungkook" }}); 
 db.Cantantes.find({ edad: { $gt: 28 }});
 db.Cantantes.find({ grupo: "BTS" });
 db.Cantantes.find({ nombre: { $gt: "Jimin" }}); 
 db.Cantantes.find({ edad: { $gt: 30 }});
 db.Cantantes.find({ grupo: "BTS" });

 db.Deportes.find();
 db.Deportes.find({ nombre: {$gt:"Fútbol" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Estadio" });
 db.Deportes.find({ nombre: {$gt:"Baloncesto" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Cancha de baloncesto" });
 db.Deportes.find({ nombre: {$gt:"Rugby" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Campo de rugby" });
 db.Deportes.find({ nombre: {$gt:"Voleibol" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Cancha de voleibol" });
 db.Deportes.find({ nombre: {$gt:"Boxeo" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Ring de boxeo" });
 db.Deportes.find({ nombre: {$gt:"Fútbol Americano" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Campo de fútbol americano" });
 db.Deportes.find({ nombre: {$gt:"Tenis" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Cancha de tenis" });
 db.Deportes.find({ nombre: {$gt:"MMA" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Octágono" });
 db.Deportes.find({ nombre: {$gt:"Cricket" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Campo de cricket" });
 db.Deportes.find({ nombre: {$gt:"Golf" }});
 db.Deportes.find({ tipo: { $gt: 17 }});
 db.Deportes.find({ lugar: "Campo de golf" });

 db.Musica.find();
 db.Musica.find({ genero: {$gt:"Pop" }});
 db.Musica.find({ integrantes: {$gt: 5 }});
 db.Musica.find({ genero: {$gt:"Rock" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"Jazz" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"Hip-Hop" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"Reguetón" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"Electrónica" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"R&B" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"Indie" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"K-pop" }});
 db.Musica.find({ integrantes: {$gt: 4 }});
 db.Musica.find({ genero: {$gt:"Salsa" }});
 db.Musica.find({ integrantes: {$gt: 6 }});
 